ID-29 Email and reset password v2
Code-4-Community/c4c-internal-backend pull request #23
Opened 2020-01-23 17:32 UTC by VishikBhalla

Added reset password functionality and implemented reset password email limiting. The Email Util class still needs the host name and id to be fully functional.

2020-01-23 18:46 UTC, rymaju requested changes
Most of this is good, I like how you seperated things into a util class, very clean. I have a couple of other suggestions though. Obviously we need to do the whole util.Date and sql.Date fix, but also we need a route that calls the reset password method that you defined. We just want a simple POST route that calls the method at the top of ApiRouter.java where we initialize all the routes, really it ought to be rate limited too so we dont spam people with emails, but if thats too much work we can seperate it onto a new ticket.

2020-01-23 18:46 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
> -import java.sql.Date;
Lets put this back in and prefix everywhere that we used it with sql.Date

2020-01-23 18:46 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
> +import java.util.Date;
Same with this, we will just prefix where you used util.Date

2020-01-23 18:46 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
> +    HashMap<String, Date> validToken = new HashMap<String, Date>();
use util.Date class

2020-01-23 18:46 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
> +        validToken.put(token, new Date());
util.Date

2020-01-24 21:21 UTC, VishikBhalla commented
I will add the changes this weekend

2020-03-31 22:25 UTC, jackblanc commented
Please provide a status update on this ticket

2020-04-19 17:41 UTC, jackblanc commented
Closing this, as no update has been provided and this PR is quite old

2020-04-19 17:41 UTC, closed without merging